# config.py

CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 30

USE_VIDEO = True
VIDEO_FRONT  = "assets/test_videos/dashcam.mp4"
VIDEO_DRIVER = "assets/test_videos/facecam.mp4"

LANE_COLOR = (0, 255, 0)
LANE_THICKNESS = 3
ROI_HEIGHT_RATIO = 0.6

YOLO_MODEL_PATH = "models/yolov8n.pt"
YOLO_CONFIDENCE = 0.5
DETECTION_CLASSES = [0, 1, 2, 3, 5, 7]  # person, bicycle, car, motorbike, bus, truck

EAR_THRESHOLD = 0.25
MAR_THRESHOLD = 0.6
DROWSY_FRAME_COUNT = 20
YAWN_FRAME_COUNT = 10

SMOOTHING_ALPHA = 0.3

COLLISION_BOX_THRESHOLD = 0.35
COLLISION_COLOR_SAFE = (0, 255, 0)
COLLISION_COLOR_WARNING = (0, 165, 255)
COLLISION_COLOR_DANGER = (0, 0, 255)

SOUND_LANE_ALERT = "assets/sounds/lane_alert.wav"
SOUND_DROWSY_ALERT = "assets/sounds/drowsy_alert.wav"
SOUND_COLLISION_ALERT = "assets/sounds/collision_alert.wav"

COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_YELLOW = (0, 255, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_ORANGE = (0, 165, 255)
